### ISSUE TITLE
is:issue is:open 想交流一下地磅的东西。你有接过顶松的吗，不知道怎么联系你。嘿嘿

### ISSUE THREAD

**Issue by pigzerowan** [yhsj0919/weigh_mock#1]
is:issue is:open 想交流一下地磅的东西。你有接过顶松的吗，不知道怎么联系你。嘿嘿

**Comment by yhsj0919** [comment]
没接过，可以加微信和github账号一样，或者你看看数据格式是不是和我模拟的两种一样就行了
